name: shopsync
description: "ShopSync - Share shopping lists with family and friends"
publish_to: "none"

version: 5.0.4-other

environment:
  sdk: ^3.6.0

dependencies:
  sentry_flutter: ^9.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  in_app_update: ^4.2.5
  intl: 0.20.2
  shared_preferences: ^2.5.4
  path_provider: ^2.0.15
  share_plus: ^12.0.1
  m3e_collection: ^0.3.7
  web: ^1.1.1
  google_sign_in: ^7.2.0
  credential_manager: ^2.0.0
  flutter_svg: ^2.1.0
  google_mobile_ads: ^7.0.0
  flutter_inappwebview: ^6.1.5
  lottie: ^3.3.2
  connectivity_plus: ^7.0.0
  home_widget: ^0.8.1
  collection: ^1.18.0
  wear_plus: ^1.2.4
  rotary_scrollbar: ^1.1.0
  http: ^1.6.0

dev_dependencies:
  sentry_dart_plugin: ^3.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  mockito: ^5.6.1
  fake_cloud_firestore: ^4.0.1
  firebase_auth_mocks: ^0.15.1
  coverage: ^1.15.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - LICENSE
    - assets/logos/
    - assets/badges/google/android/png@4x/dark/android_dark_rd_ctn@4x.png
    - assets/badges/google/android/png@4x/dark/android_dark_sq_ctn@4x.png
    - assets/badges/google/android/png@4x/light/android_light_rd_ctn@4x.png
    - assets/badges/google/android/png@4x/light/android_light_rd_na@4x.png
    - assets/badges/google/android/png@4x/light/android_light_sq_ctn@4x.png
    - assets/badges/google/android/png@4x/dark/android_dark_rd_na@4x.png
    - assets/badges/google/android/png@4x/dark/android_dark_sq_na@4x.png
    - assets/icons/food_icons/bakery/
    - assets/icons/food_icons/berries/
    - assets/icons/food_icons/desserts/
    - assets/icons/food_icons/dishes/
    - assets/icons/food_icons/drinks/
    - assets/icons/food_icons/fastfood/
    - assets/icons/food_icons/fruits/
    - assets/icons/food_icons/ingredients/
    - assets/icons/food_icons/kawaii/
    - assets/icons/food_icons/meat/
    - assets/icons/food_icons/nutrition/
    - assets/icons/food_icons/nuts/
    - assets/icons/food_icons/pastries/
    - assets/icons/food_icons/seafood/
    - assets/icons/food_icons/vegetables/
    - assets/icons/food_icons/other/
    - assets/animations/no_internet.json

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: shopsync
  org: aadishsdev
