name: CD-Prod-Play-WearOS

on:
  workflow_dispatch:

jobs:
  cd-build-and-upload:
    name: CD-Build and Upload WearOS to Google Play Production
    environment: google-play-deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"

      # Step 2: Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          cache: true

      # Step 2.5: Cache Android SDK, NDK, and CMake
      - name: Cache Android SDK, NDK, and CMake
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/Android/sdk/ndk/27.0.12077973
            /home/runner/Android/sdk/platforms/android-31
            /home/runner/Android/sdk/cmake/3.22.1
          key: android-tools-${{ runner.os }}-ndk-27-sdk-31-cmake-3.22.1
          restore-keys: |
            android-tools-${{ runner.os }}-

      # Step 3: Decode Keystore (from GitHub Secret)
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release-key.jks
        working-directory: android

      # Step 4: Create key.properties (using GitHub secrets)
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> key.properties
          echo "storeFile=release-key.jks" >> key.properties
        working-directory: android

      # Step 5: Create sentry.properties (using GitHub secrets)
      - name: Create sentry.properties
        run: |
          echo "${{ secrets.SENTRY_PROPERTIES }}" >> sentry.properties

      # Step 6: Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # Step 7: Build AAB (Android App Bundle) for WearOS release
      - name: Build WearOS AAB
        run: flutter build appbundle --release --flavor wear --target=lib/wear/wear_main.dart

      # Step 8: Upload the generated WearOS AAB to Google Play Console
      - name: Upload WearOS to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.aadishsamir.shopsync
          releaseFiles: build/app/outputs/bundle/wearRelease/app-wear-release.aab
          track: wear:production

